# build environment
FROM node:12.18.4

WORKDIR /app

RUN mkdir frontend
RUN ls
COPY ./.env.production ./.env.production
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./build ./build
COPY ./node_modules ./node_modules
COPY ./frontend/build ./frontend/build
RUN ls

# Запуск проекта
CMD npm run start:prod
